config/routes.rb
Websitewmo::Application.routes.draw do

  match 'contact/form' => 'contact#new', :as => 'contact', :via => :get
  match 'contact/form' => 'contact#create', :as => 'contact', :via => :post
  match 'meldpunt' => 'mention#new', :as => 'meldpunt', :via => :get
  match 'meldpunt' => 'mention#create', :as => 'meldpunt', :via => :post

  resources :posts
  resources :pages
  resources :categories
  resources :contact

  root :to => 'pages#home' , category_id: [1,2,3]
  

  get "wmo" => "pages#actual", as: 'wmo', category_id: 1
  get "wgt" => "pages#actual", as: 'wgt', category_id: 2
  get "algemeen" => "pages#actual", as: 'algemeen', category_id: 3
  get "nieuwsoverzicht" => "pages#actual_news", as: 'nieuwsoverzicht', category_id: [1,2,3]
  
  get "prestatievelden" => "pages#info", as: 'prestatievelden'
  get "afkortingen" => "pages#info_shorts", as: 'afkortingen', category_id: 4
  get "tips" => "pages#info", as: "tips", category_id: 5

  get "faq" => "pages#contact", as: 'faq', category_id: 6
  get "links" => "pages#contact", as: 'links', category_id: 7
  get "adressen" => "pages#contact_adressen", as: "adressen"
  

  match '/about',     to: 'pages#about'
  match '/informatie',to: 'pages#info'
  match '/actual',    to: 'pages#actual'
  match '/meldpunt',  to: 'pages#hotline'
  match '/over_wgt', to: 'pages#about_wgt'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :posts
end

app/models/mentionmessage.rb
class Mentionmessage

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :category, :subject, :body

  validates_inclusion_of :category, in: %([Openbaar vervoer],[Gebouwen], [Op straat],[Overige])
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :category, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates_inclusion_of :category, in: %w(Openbaar vervoer Regelingen Bestrating Openbare voorzieningen Overige)
  validates :email, :format => { :with => %r{.+@.+\..+} }
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :category_id, :content, :name, :title

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

def index
	@categories = Category.all
end

def show
	@category = Category.find(params[:id])
end

def new
	@category = Category.new	
end

def create
	@category = Category.new(params[:category])
	if @category.save
		redirect_to categories_path, :notice => "Gelukt"
	else
		render "new"
	end
end

def destroy
	@category = Category.find(params[:id])
	@category.destroy

	redirect_to categories_path, :notice => "Hij is verdwenen"
end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      ContactMailer.new_message(@message).deliver
      redirect_to(contact_path, :notice => "Bericht verzonden!")
    else
      flash.now.alert = "Niet alles is ingevuld"
      render :new
    end
  end

end

app/controllers/mention_controller.rb
class MentionController < ApplicationController

  def new
    @mentionmessage = Mentionmessage.new
  end

  def create
    @mentionmessage = Mentionmessage.new(params[:mentionmessage])
    
    if @mentionmessage.valid?
      MentionMailer.new_message(@mentionmessage).deliver
      redirect_to(meldpunt_path, :notice => "Bericht verzonden!")
    else
      flash.now.alert = "Niet alles is ingevuld"
      render :mention_new
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
	#@posts = Post.limit(2).order('id desc').all
	@posts= Post.where(category_id: params[:category_id]).limit(2).order('id desc').all
	#@posts = Post.where("Category = ?", 'algemeen').all
	#WYSIWYG editor via jquery of misschien een gem ? niet vergeten 
	#Waarom is de teaxaeara resizelble?
	# alle CMS via posts laten verlopen, kan mooi zo.
	#Script vinden voor FAQ inschuiven of verspringen.
	#Ander script zoeken voor constrast? 
	#Kijken naar de internalization gem 
  	@title = "Home"
  end

 def contact
 	@questions = Post.where(category_id: params[:category_id]).all
	@categories = Category.all
	@catname = Post.where(category_id: params[:category_id]).limit(1).order('id desc').all
	@title = "Contact"
 end

  def actual
 	@actual = Post.where(category_id: params[:category_id]).order('id desc').all
 	@catname = Post.where(category_id: params[:category_id]).limit(1).order('id desc').all
 	@title = "Actueel"
 end

 def actual_news
 	@actual = Post.where(category_id: params[:category_id]).order('id desc').all
 	@catname = Post.where(category_id: params[:category_id]).limit(1).order('id desc').all
 	@title = "Actueel"
 end

def info_shorts
	@shorts = Post.where(category_id: params[:category_id]).order('id desc').all
	@catname = Post.where(category_id: params[:category_id]).limit(1).order('id desc').all
	@title = "Afkortingen"
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

def index
	@posts = Post.all
end

def show
	@post = Post.find(params[:id])
end

def new
	@post = Post.new
end

def create
	@post = Post.new(params[:post])
	if @post.save
		redirect_to posts_path, :notice => "Gelukt"
	else
		render "new"
	end
end

def edit
	@post = Post.find(params[:id])
end

def update
	@post = Post.find(params[:id])		

	if @post.update_attributes(params[:post])
		redirect_to posts_path, :notice => "post has been updated"
	else
		render "edit"
	end
end

def destroy
	@post = Post.find(params[:id])
	@post.destroy

	redirect_to posts_path, :notice => "Hij is verdwenen"
end

end

app/helpers/application_helper.rb
module ApplicationHelper

def logo
	image_tag("logo.jpg", :alt => "Logo's WMO adviesraad en Werkgroep toegankelijkheid", :class => "round")
end

def text_large_img
	image_tag("tekst_vergroter_large.jpg", :alt => "Tekst vergroten",  title: "Vergroten")
end

def text_normal_img
	image_tag("tekst_vergroter_normal.jpg", :alt => "Tekst normaal", title: "Normaal")
end

def text_small_img
	image_tag("tekst_vergroter_small.jpg", :alt => "Tekst kleiner", title: "Verkleinen")
end

def contrast_img
	image_tag("contrast.jpg", :alt => "Contrast", title: "Contrast")
end

def sound_img
	image_tag("geluid.jpg", :alt => "Voorlezen", title: "Voorlezen")
end

def home_img
	image_tag("home.jpg", :alt => "Tekst normaal", title: "Home")
end

def about_img
	image_tag("over_ons.jpg", :alt => "Tekst normaal", title: "Over ons")
end

def info_img
	image_tag("info.jpg", :alt => "Tekst normaal", title: "Informatie")
end

def actual_img
	image_tag("actueel.jpg", :alt => "Tekst normaal", title: "Actueel")
end

def hotline_img
	image_tag("meldpunt.jpg", :alt => "Tekst normaal", title: "Meldpunt")
end

def contact_img
	image_tag("contact.jpg", :alt => "Tekst normaal", title: "Contact")
end

def pijltje_img
	image_tag("pijl_overons.png", :alt => "pijl_overons")
end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/mention_helper.rb
module MentionHelper
end

app/helpers/pages_helper.rb
module PagesHelper

def cat_right_img
	image_tag("cat.jpg", :alt => "Plaatje kat", :class => "cat_right")
end

def cat_left_img
	image_tag("cat.jpg", :alt => "Plaatje kat", :class => "cat_left")
end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<h1>Overzicht</h1>

	<% @categories.each do |p| %>
<p>
<%= link_to p.name, p %> | 
<%= link_to "verwijder", p, :confirm => "Weet je het zeker?", :method => :delete %> 
</p>


	<% end %>

app/views/categories/new.html.erb
<h1>Nieuwe</h1>

<%= form_for @category do |f| %>
	<p>
	<%= f.label :name, "Categorie Naam:" %><br />
	<%= f.text_field :name %>
	</p>

<p> <%= f.submit "Toevoegen" %></p>
<% end %>

app/views/categories/show.html.erb
<h1>Details van de Post</h1>

<ul>
<li><%= @category.name %></li>

</ul>

app/views/contact/new.html.erb
<div id="navigation_violet">
  <ul class="navi"><p>
    <li><strong><%= link_to "Adressen", adressen_path %></a></li></strong>
    <li><strong><%= link_to "| Contact Opnemen", contact_path %></a></li></strong>
    <li><strong><%= link_to "| Veel gestelde vragen", faq_path  %></a></li></strong>
    <li><strong><%= link_to "| Handige Links", links_path  %></a></li></strong>
    <li><strong><a href="#">| Vacatures |</a></li></p></strong>
  </ul>
</div>

<div id="content">
  <h1 id="violet">Hier kunt u contact opnement via de mail.</h1>
<% flash.each do |key, value| %>
  <div class="flash <%= key %>"><%= value %></div>
<% end %>
<%= form_for @message, :url => contact_path do |form| %>
    <div class="field">

      <p><%= form.label :name, "Uw naam:" %></p>
      <p><%= form.text_field :name %></p>
   
      <p><%= form.label :email, "Uw e-mail adres:" %></p>
      <p><%= form.text_field :email %></p>

      <p>Waarover wilt u contact opnemen?</p>
      <p id="radiobutton"><%= form.radio_button(:category, "Openbaar vervoer") %> Openbaar vervoer</p>
      <p id="radiobutton"><%= form.radio_button(:category, "Regelingen") %> Gebouwen</p>
      <p id="radiobutton"><%= form.radio_button(:category, "straat") %> Op straat</p>
      <p id="radiobutton"><%= form.radio_button(:category, "Overige") %> Overige</p> <br/>

      <p><%= form.label :subject, "Onderwerp:" %></p>
      <p><%= form.text_field :subject %></p>
    
      <p><%= form.label :body, "Inhoud:" %></p>
      <p><%= form.text_area :body, :cols => 55, :rows => 5 %></p>
      <p class="submit"><%= form.submit "Verzenden" %></p>
     </div>
<% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
<div id="footercenter">
 
	<ul class="footnav">
	<li><strong>Navigatie</strong></li>
	<li><%= link_to 'Home', root_path %></a></li>
	<li><%= link_to 'Over ons', about_path %></a></li>
	<li><%= link_to 'Informatie', informatie_path %></a></li>
	<li><%= link_to 'Actueel', nieuwsoverzicht_path %> </a></li>
	<li><%= link_to 'Meldpunt', meldpunt_path %></a></li>
	<li><%= link_to 'Contact', contact_path %></a></li>
	</ul>    



	<ul class="footnav">
	<li><strong>Site</strong></li>
	<li><a href="sitemap.html">Sitemap</a></li>
	<li><a href="privacy.html">Privacy statement</a></li>
	</ul>

	<ul class="footnav">
	<li><strong>Adresgegevens</strong></li>
	<li>WMO Leeuwarden</li>
	<li>Nieuw Sonnenborgh 58</li>
	<li>8916 DA  Leeuwarden</li>
	<li><strong>T</strong>   058 - 212 74 15</li>
	<li><strong>M</strong>   06 - 46 29 33 29</li>
	<li><strong>E</strong>   <a href="mailto:info@wmo-leeuwarden.nl">info@wmo-leeuwarden.nl</a></li>
	</ul>
	</div>
</footer>

	</body>

app/views/layouts/_header.html.erb
<body>
<nav>
	<img class="logo"><a href="#"><%= link_to logo %></a>
<ul class="top_items">
	<li ><%= link_to text_large_img, "#", id: "up" %></a></li>
	<li ><%= link_to text_normal_img, '#', id: "reset" %></a></li>
	<li ><%= link_to text_small_img, '#', id: "down" %></a></li>
	<li class="contrast"><a href="#" rel="/assets/style.css"><%= contrast_img %></a></li>
    <li class="contrast"><a href="#" rel="/assets/blackwhite.css"><%= contrast_img %></a></li>
	<li ><%= link_to sound_img %></li>
</ul>
</nav>

<header id="buttons">
<ul>

	<li class="home"><%= link_to "", root_path, title: "hallo" %></a></li>
	<li class="about"><%= link_to "", '/about' %></a></li>
	<li class="info"><%= link_to "", '/informatie' %></a></li>
	<li class="actual"><%= link_to "", nieuwsoverzicht_path  %>
	<li class="hotline"><%= link_to "", meldpunt_path %></a></li>
	<li class="contact"><%= link_to "", adressen_path %></a></li>

</ul>  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WMO Adviesraad & Werkgroep Toegankelijkheid | <%= @title %></title>
	  	<%= csrf_meta_tags %>
		<%= stylesheet_link_tag "style", media: "all" %>
		<%= javascript_include_tag "application" %>

	<script type="text/javascript">
		if($.cookie("css")) {
			$("link").attr("href",$.cookie("css"));
		}
		$(document).ready(function() { 
			$(".contrast a").click(function() { 
				$("link").attr("href",$(this).attr('rel'));
				$.cookie("css",$(this).attr('rel'), {expires: 365, path: '/'});
				return false;
			});
		});
	</script>
	
		<script type="text/javascript">

			$(document).ready(function(){
			 $("#up").fontscale("p","up",{unit:"px", increment:2});
			 $("#down").fontscale("p","down",{unit:"px", increment:2});
			 $("#reset").fontscale("p","reset");
			});
	</script>

</head>
<body>
<div id="container" >
	<%= render 'layouts/header' %>

	<%= yield %>
</div>
	<%= render 'layouts/footer' %>


</body>
</html>

app/views/mention/new.html.erb
<div id="content">
  <h1 id="darkblue">Maak een melding:</h1>
<% flash.each do |key, value| %>
  <div class="flash <%= key %>"><%= value %></div>
<% end %>

<%= form_for @mentionmessage, :url => meldpunt_path do |form| %>
    <div class="mention_field">

      <p><%= form.label :name, "Uw naam: (laat leeg als u anoniem wil blijven)" %></p>
      <p><%= form.text_field :name %></p>
   
      <p><%= form.label :email, "Uw e-mail adres: (laat leeg als u anoniem wil blijven)" %></p>
      <p><%= form.text_field :email %></p>

      <p>Waarover heeft u een melding?</p>
      <p id="radiobutton"><%= form.radio_button(:category, "Openbaar vervoer") %> Openbaar vervoer</p>
      <p id="radiobutton"><%= form.radio_button(:category, "Regelingen") %>       Gebouwen</p>
      <p id="radiobutton"><%= form.radio_button(:category, "straat") %>           Op straat</p>
      <p id="radiobutton"><%= form.radio_button(:category, "Overige") %>          Overige</p><br/>

      <p><%= form.label :subject, "Onderwerp:" %></p>
      <p><%= form.text_field :subject %></p>
    
      <p><%= form.label :body, "Inhoud" %></p>
      <p><%= form.text_area :body, :cols => 55, :rows => 5 %></p>
      <p class="mention_submit"><%= form.submit "Verzenden" %></p>
     </div>
    <% end %>
</div>

app/views/pages/about_wgt.html.erb
<div id="navigation_orange">
	<ul class="navi"><p>
		<li><strong><%= link_to "WMO Adviesraad", about_path %></a></li></strong>
		<li><strong><%= link_to "| Werkgroep Toegankelijkheid |", '/over_wgt' %></a></li></p></strong>
	</ul>
</div>

<div id="content"><!-- Hier begint de content -->
<h1 id= "orange">Over de Werkgroep Toegankelijkheid</h1>
<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis consequat volutpat lectus in iaculis. 
Nam sit amet orci et neque auctor suscipit in ut nibh. Etiam ac nibh sapien, eget auctor sapien. Etiam mollis imperdiet arcu. 
Quisque accumsan posuere urna, quis laoreet leo rutrum a. Nunc porttitor felis neque. Nunc euismod lacinia tellus, nec scelerisque metus 
condimentum sit amet. Cras venenatis lacus at erat sagittis condimentum. Sed eget velit neque. Donec accumsan adipiscing consequat. 
Vivamus eu arcu ac lectus scelerisque pharetra. Duis dolor erat, dictum blandit lobortis id, accumsan vel ipsum. Vestibulum ante ipsum primis 
in faucibus orci luctus et ultrices posuere cubilia Curae; Ut orci libero, porta sit amet feugiat ut, egestas at purus. Vestibulum venenatis 
facilisis dignissim. Quisque ac feugiat odio.</p>
</div>

app/views/pages/actual.html.erb
<div id="navigation_lightblue">
	<ul class="navi"><p>
		<li><strong><%= link_to "Nieuwsoverzicht", nieuwsoverzicht_path  %></a></li></strong>
		<li><strong><%= link_to "| WMO Adviesraad", wmo_path  %></a></li></strong>
		<li><strong><%= link_to "| Werkgroep Toegankelijkheid", wgt_path  %></a></li></strong>
		<li><strong><%= link_to "| Algemeen |", algemeen_path  %></a></li></p></strong>
	</ul>
</div>
<div id="content">
	<% @catname.each do |c| %>
		<h1 id= "lightblue"><%= c.category.name %></h1>
	<% end %>
	
	<% @actual.each do |a| %>

		<h2 id="lightblue"><%= a.name %></h2>
		<strong><p><%= a.created_at.strftime("%H:%M %d-%m-%Y") %> &#124; Auteur: <%= a.category.name %></p></strong>
		<p><%= truncate a.content, length: 100 %> </p>
		<p id="artikellink_lightblue"><%= link_to 'Lees meer', a %></a></p>
<% end %>
</div>

app/views/pages/actual_news.html.erb
<div id="navigation_lightblue">
	<ul class="navi"><p>
		<li><strong><%= link_to "Nieuwsoverzicht", nieuwsoverzicht_path  %></a></li></strong>
		<li><strong><%= link_to "| WMO Adviesraad", wmo_path  %></a></li></strong>
		<li><strong><%= link_to "| Werkgroep Toegankelijkheid", wgt_path  %></a></li></strong>
		<li><strong><%= link_to "| Algemeen |", algemeen_path  %></a></li></p></strong>
	</ul>
</div>

<div id="content">

<% @actual.each do |a| %>

		<h1 id= "lightblue"><%= a.category.name %></h1>
		<h2 id= "lightblue"><%= a.name %></h2>
		<strong><p><%= a.created_at.strftime("%H:%M %d-%m-%Y") %> &#124; Auteur: <%= a.category.name %></p></strong>
		<p><%= truncate a.content, length: 100 %> </p>
		<p id="artikellink_lightblue"><%= link_to 'Lees meer', a %></a></p>
<% end %>
</div>

app/views/pages/contact.html.erb
<div id="navigation_violet">
	<ul class="navi"><p>
		<li><strong><%= link_to "Adressen", adressen_path %></a></li></strong>
		<li><strong><%= link_to "| Contact Opnemen", contact_path %></a></li></strong>
		<li><strong><%= link_to "| Veel gestelde vragen", faq_path  %></a></li></strong>
		<li><strong><%= link_to "| Handige Links", links_path  %></a></li></strong>
		<li><strong><a href="#">| Vacatures |</a></li></p></strong>
	</ul>
</div>
<div id="content">
<% @catname.each do |c| %>
	<h1><%= c.category.name %></h1>
<% end %>

<% @questions.each do |p| %>
	<p><%= link_to p.name, p %></p>
	<p><%= p.content %></p>
	<p><%= link_to "verwijder", p, :confirm => "Weet je het zeker?", :method => :delete %> 
<% end %>
</div>

app/views/pages/contact_adressen.html.erb
<div id="navigation_violet">
	<ul class="navi"><p>
		<li><strong><%= link_to "Adressen", adressen_path %></a></li></strong>
		<li><strong><%= link_to "| Contact Opnemen", contact_path %></a></li></strong>
		<li><strong><%= link_to "| Veel gestelde vragen", faq_path  %></a></li></strong>
		<li><strong><%= link_to "| Handige Links", links_path  %></a></li></strong>
		<li><strong><a href="#">| Vacatures |</a></li></p></strong>
	</ul>
</div>
<div id="content">
<h1 id="violet">Adressen</h1>
<ul>
	<li><p>Adresgegevens</p></li>
	<li><p>WMO Leeuwarden</p></li>
	<li><p>Nieuw Sonnenborgh 58</p></li>
	<li><p>8916 DA Leeuwarden</p></li>
	<li><p>T 058 - 212 74 15</p></li>
	<li><p>M 06 - 46 29 33 29</p></li>
	<li><p><%= link_to "E info@wmo-leeuwarden.nl", contact_path %></p></li>
</ul>

</div>

app/views/pages/home.html.erb
<div>
	<h1 id= "red">Welkom op de nieuwe website (beta v0.2)</h1>
		<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse suscipit, 
		turpis bibendum bibendum lobortis, urna leo aliquam tellus, a accumsan nibh mi 
		ut sem. Suspendisse elit lectus, porttitor eget placerat non, suscipit ac magna
		Integer accumsan ullamcorper imperdiet.Suspendisse elit lectus, porttitor eget 
		placerat non, suscipit ac magna. Integer accumsan ullamcorper imperdiet.
		</p>
	<p id="artikellink_red">
		<%= link_to 'Lees meer over WMO en Werkgroep toegankelijkheid >>>', about_path %></a>
	</p>
</div>

<% @posts.each do |p| %>

<div class="homenieuws">

	<h2 id= "red"><%= p.name %></h2>
	<%= link_to cat_left_img %>	
	<p class="homenieuwstext">
	<strong><%= p.created_at.strftime("%d-%m-%Y") %></strong><br /> <!--<nog weg halen, indeling bespreken-->
	<%= truncate p.content, length: 50 %> 
 	</p>
	<p class= "leesmeer"><%= link_to 'Lees meer...', p %></a></p>
	
</div>

<% end %> 

app/views/pages/info.html.erb
<div id="navigation_green">
	<ul class="navi"><p>
		<li><strong><%= link_to 'Prestatievelden 3-6', prestatievelden_path %></a></li></strong>
		<li><strong><%= link_to '| Afkortingen', '/afkortingen' %> </a></li></strong>
		<li><strong><a href="#">| Tips </a></li></strong>
		<li><strong><a href="#">| Downloads | </a></li></strong>
	</ul>
</div>

<div id="content">
	<h1 id="green">Prestatievelden 3-6</h1>
		<p>
		Onder de prestatievelden 3, 4, 5 en 6 vallen de volgende dingen:
		</p>

	<h2 id="green">
		<p>Prestatieveld 3 (informatie, advies en cliëntondersteuning)
		</p>
	</h2>
		<p>
		De WMO adviesraad geeft informatie en advies aan de burgers om het verloop in de maatschappij te versoepelen. Het advies wat gegeven wordt is erg divers en kan over alle zaken gaan. Bijvoorbeeld over algemene voorzieningen als informatiepunten. Maar ook specifieker zoals individueel advies. Bijvoorbeeld dat een slechtziende iets wil ondernemen maar niet weet hoe het moet en wat de makkelijkste manier is.
		</p>

	<h2 id="green">
		<p>
		Prestatieveld 4 (Mantelzorgers en vrijwilligers)
		</p>
	</h2>
		<p>
		Mantelzorg is langdurige zorg voor bijvoorbeeld gehandicapten door familie, vrienden. Het is intensief en zwaar. Daarom wordt het begeleid en ondersteund door de WMO.
		</p>

	<h2 id="green">
		<p>
		Prestatieveld 5
		</p>
	</h2>
		<p>
		Hier gaat het om algemene maatregelen om inwoners te stimuleren om deel te nemen aan de maatschappij. Dit is bijvoorbeeld bedoeld om kwetsbare groepen weer actief mee te laten doen aan het sociale leven.
		Ook de toegankelijkheid van openbare ruimten zoals het station en musea of algemene voorzieningen zoals rolstoelvervoer of gehandicaptentoilet vallen onder dit prestatieveld.
		<p>

	<h2 id="green">
		<p>
		Prestatieveld 6
		</p>
	</h2>
		<p>
		Hier worden mensen met een beperking of chronisch psychisch of psychosociaal probleem die niet zonder hulp kunnen functioneren geholpen. Het doel is om beter zelfstandig te kunnen functioneren. Voorbeelden zijn rolstoelen, gehandicaptenvervoer, woningaanpassingen en thuiszorg.
		</p>
</div>

app/views/pages/info_shorts.html.erb
<div id="navigation_green">
	<ul class="navi"><p>
		<li><strong><%= link_to 'Prestatievelden 3-6', prestatievelden_path %></a></li></strong>
		<li><strong><%= link_to '| Afkortingen', '/afkortingen' %> </a></li></strong>
		<li><strong><a href="#">| Tips </a></li></strong>
		<li><strong><a href="#">| Downloads | </a></li></strong>
	</ul>
</div>

<div id="content">
	<% @catname.each do |c| %>
		<h1 id="green"><%= c.category.name %></h1>
	<% end %>

	<% @shorts.each do |s| %>

		<h2 id="green"><%= s.name %></h2>
		<p><%= truncate s.content, length: 100 %> </p>

<% end %>

</div>

app/views/posts/edit.html.erb
<h1>Nieuwe</h1>

<%= form_for @post do |f| %>
	<p>
	<%= f.collection_select(:category_id, Category.all, :id, :name) %>
	</p>

	<p>
		<%= f.label :name, "Naam" %> <br />
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :title, "title" %> <br />
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :content, "Inhoud" %> <br />
		<%= f.text_field :content %>
	</p>

<p> <%= f.submit "Toevoegen" %></p>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |p| %>
<p>
<%= link_to p.name, p %> | 
<%= link_to "Edit", edit_post_path(p) %> |
<%= link_to "verwijder", p, :confirm => "Weet je het zeker?", :method => :delete %> 
</p>

<% end %>

app/views/posts/new.html.erb
<h1>Nieuwe</h1>

<%= form_for @post do |f| %>
	<p>
	<%= f.collection_select(:category_id, Category.all, :id, :name) %>
	</p>

	<p>
		<%= f.label :name, "Naam" %> <br />
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :title, "title" %> <br />
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :content, "Inhoud" %> <br />
		<%= f.text_field :content %>
	</p>

<p> <%= f.submit "Toevoegen" %></p>
<% end %>

app/views/posts/show.html.erb
<h1>Details van de Post</h1>


<p><%= @post.category.name %></p>
<p><%= @post.name %></p>
<p><%= @post.content %></p>